#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# build-from-source.sh — Path B for the kvendra-reference-stack.
#
# Clones the upstream Kvendra repos, builds the docker images locally
# (no pull from ghcr.io), and writes a docker-compose.override.yml that
# points each `image:` to the locally-built tag.
#
# Audience: banks, regulated teams, security audits — anyone who needs
# to compile every Kvendra component from public source before running.
#
# Upstream images we still pull from public registries (these are
# themselves open-source projects, listed for transparency):
#   - pgvector/pgvector:pg16    — Postgres + pgvector
#   - ollama/ollama:0.24.0      — Ollama runtime
#   - postgres:16-alpine        — backup sidecar
# To rebuild THOSE from source as well, see docs/troubleshooting.md
# § "Fully from-source build".

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SOURCES_DIR="${SOURCES_DIR:-$ROOT/sources}"
PLATFORM_REPO="${PLATFORM_REPO:-https://github.com/KvendraAI/kvendra-platform.git}"
PLATFORM_REF="${PLATFORM_REF:-main}"
LOCAL_TAG="kvendra-platform:local"

mkdir -p "$SOURCES_DIR"

# ----------------------------------------------------------------------
# 1. Clone or refresh kvendra-platform.
# ----------------------------------------------------------------------
if [[ -d "$SOURCES_DIR/kvendra-platform/.git" ]]; then
  echo "build-from-source: updating existing clone of kvendra-platform"
  git -C "$SOURCES_DIR/kvendra-platform" fetch origin
  git -C "$SOURCES_DIR/kvendra-platform" checkout "$PLATFORM_REF"
  git -C "$SOURCES_DIR/kvendra-platform" pull --ff-only origin "$PLATFORM_REF" || true
else
  echo "build-from-source: cloning $PLATFORM_REPO (ref=$PLATFORM_REF)"
  git clone --depth 1 --branch "$PLATFORM_REF" "$PLATFORM_REPO" "$SOURCES_DIR/kvendra-platform"
fi

COMMIT=$(git -C "$SOURCES_DIR/kvendra-platform" rev-parse --short HEAD)
echo "build-from-source: kvendra-platform at commit $COMMIT"

# ----------------------------------------------------------------------
# 2. Build the local docker image.
# ----------------------------------------------------------------------
echo "build-from-source: building $LOCAL_TAG from $SOURCES_DIR/kvendra-platform"
docker build \
  --tag "$LOCAL_TAG" \
  --label "org.kvendra.commit=$COMMIT" \
  --label "org.kvendra.source=local-build" \
  "$SOURCES_DIR/kvendra-platform"

# ----------------------------------------------------------------------
# 3. Write docker-compose.override.yml so `up.sh` picks the local image.
# ----------------------------------------------------------------------
OVERRIDE="$ROOT/docker-compose.override.yml"
cat >"$OVERRIDE" <<EOF
# SPDX-License-Identifier: MIT
# Generated by scripts/build-from-source.sh — do not edit manually.
# Re-run build-from-source.sh to refresh.
#
# This override switches kvendra-platform from the ghcr.io image to a
# locally-built image (commit $COMMIT).

services:
  kvendra-platform:
    image: $LOCAL_TAG
EOF

echo
echo "==============================================="
echo "build-from-source: ok."
echo
echo "local image:        $LOCAL_TAG  (commit $COMMIT)"
echo "compose override:   $OVERRIDE"
echo
echo "next:  ./scripts/up.sh"
echo "(up.sh will pick up the override automatically.)"
